In [95]:
import pandas as pd
sales_df=pd.read_csv('C:/Users/Meenakshi/Desktop/Machine Learning IIMB/data/Advertising.csv')

In [96]:
sales_df.head(5)

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [97]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
Unnamed: 0    200 non-null int64
TV            200 non-null float64
Radio         200 non-null float64
Newspaper     200 non-null float64
Sales         200 non-null float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB


In [98]:
sales_df.drop("Unnamed: 0", axis=1)

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
5      8.7   48.9       75.0    7.2
6     57.5   32.8       23.5   11.8
7    120.2   19.6       11.6   13.2
8      8.6    2.1        1.0    4.8
9    199.8    2.6       21.2   10.6
10    66.1    5.8       24.2    8.6
11   214.7   24.0        4.0   17.4
12    23.8   35.1       65.9    9.2
13    97.5    7.6        7.2    9.7
14   204.1   32.9       46.0   19.0
15   195.4   47.7       52.9   22.4
16    67.8   36.6      114.0   12.5
17   281.4   39.6       55.8   24.4
18    69.2   20.5       18.3   11.3
19   147.3   23.9       19.1   14.6
20   218.4   27.7       53.4   18.0
21   237.4    5.1       23.5   12.5
22    13.2   15.9       49.6    5.6
23   228.3   16.9       26.2   15.5
24    62.3   12.6       18.3    9.7
25   262.9    3.5       19.5   12.0
26   142.9   29.3       12.6   15.0
27   240.1   16.7       22.9   15.9
28   248.8   27.1       22.9   18.9
29    70.6   16.0       40.8   10.5
..     ...    ...        ...    ...
170   50.0   11.6       18.4    8.4
171  164.5   20.9       47.4   14.5
172   19.6   20.1       17.0    7.6
173  168.4    7.1       12.8   11.7
174  222.4    3.4       13.1   11.5
175  276.9   48.9       41.8   27.0
176  248.4   30.2       20.3   20.2
177  170.2    7.8       35.2   11.7
178  276.7    2.3       23.7   11.8
179  165.6   10.0       17.6   12.6
180  156.6    2.6        8.3   10.5
181  218.5    5.4       27.4   12.2
182   56.2    5.7       29.7    8.7
183  287.6   43.0       71.8   26.2
184  253.8   21.3       30.0   17.6
185  205.0   45.1       19.6   22.6
186  139.5    2.1       26.6   10.3
187  191.1   28.7       18.2   17.3
188  286.0   13.9        3.7   15.9
189   18.7   12.1       23.4    6.7
190   39.5   41.1        5.8   10.8
191   75.5   10.8        6.0    9.9
192   17.2    4.1       31.6    5.9
193  166.8   42.0        3.6   19.6
194  149.7   35.6        6.0   17.3
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [99]:
sales_df=sales_df.drop("Unnamed: 0", axis=1)
sales_df[0:5]

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [100]:
sales_df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

### Set X and Y Variables

In [101]:
Y=sales_df.Sales
X=pd.DataFrame(sales_df.TV)


### Split Dataset into Train and Test

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, train_size=0.8, random_state=100)

In [103]:
X_train.shape

(160, 1)

In [104]:
X_test.shape

(40, 1)

In [105]:
X_train[0:5]

TV
168  215.4
112  175.7
171  164.5
181  218.5
7    120.2

### Build a Model

### Linear Regression

In [106]:
from sklearn.linear_model import LinearRegression

In [107]:
lreg_v1=LinearRegression()

In [108]:
lreg_v1.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [109]:
lreg_v1.intercept_

7.113008222196275

In [110]:
lreg_v1.coef_

array([0.04610976])

### Predict on test set

In [111]:
Y_pred_v1=lreg_v1.predict(X_test)

In [112]:
Y_df_v1=pd.DataFrame({"Actual": Y_test, "Predicted": Y_pred_v1, "Residual": Y_test- Y_pred_v1})

In [113]:
Y_df_v1[0:5]

Actual  Predicted  Residual
126     6.6   7.472664 -0.872664
104    20.7  18.096352  2.603648
99     17.2  13.347047  3.852953
92     19.4  17.151102  2.248898
111    21.8  18.257736  3.542264

### Metrics:MSE

In [114]:
from sklearn.metrics import mean_squared_error

In [115]:
mse_v1=mean_squared_error(Y_df_v1.Actual,Y_df_v1.Predicted)

In [116]:
import numpy as np

In [117]:
np.sqrt(mse_v1)

3.1124057492381794

### R Squared

In [118]:
lreg_v1.score(X_train, Y_train)

0.6197569503198974

In [119]:
lreg_v1.score(X_test, Y_test)

0.5441581483697225

In [120]:
from sklearn.metrics import r2_score

In [121]:
r2_score(Y_df_v1.Actual, Y_df_v1.Predicted)

0.5441581483697225

### Multiple Linear Regression

In [122]:
Y=sales_df.Sales
X=pd.DataFrame(sales_df[['TV', 'Radio','Newspaper']])

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, train_size=0.8, random_state=100)

In [124]:
X_train.shape

(160, 3)

In [125]:
X_test.shape

(40, 3)

In [126]:
from sklearn.linear_model import LinearRegression

In [127]:
lreg_v1=LinearRegression()

In [128]:
lreg_v1.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [129]:
lreg_v1.intercept_

2.8172751352950005

In [130]:
lreg_v1.coef_

array([0.0455864 , 0.18569816, 0.00223281])

In [131]:
Y_pred_v1=lreg_v1.predict(X_test)

In [132]:
Y_df_v1=pd.DataFrame({"Actual": Y_test, "Predicted": Y_pred_v1, "Residual": Y_test- Y_pred_v1})

In [133]:
Y_df_v1[0:5]

Actual  Predicted  Residual
126     6.6  10.509488 -3.909488
104    20.7  20.057236  0.642764
99     17.2  16.826655  0.373345
92     19.4  19.094058  0.305942
111    21.8  20.943838  0.856162

In [134]:
from sklearn.metrics import mean_squared_error

In [135]:
lreg_v1.score(X_test, Y_test)

0.9184369032278498

In [136]:
from sklearn.metrics import r2_score

In [137]:
r2_score(Y_df_v1.Actual, Y_df_v1.Predicted)

0.9184369032278497

### Add an interaction variable

In [138]:
X['tv_radio']=X['TV']*X['Radio']

In [139]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, train_size=0.8, random_state=100)

In [140]:
X_train.shape

(160, 4)

In [141]:
from sklearn.linear_model import LinearRegression

In [142]:
lreg_v1=LinearRegression()

In [143]:
lreg_v1.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [144]:
lreg_v1.intercept_

6.52683496801847

In [145]:
lreg_v1.coef_

array([0.01956588, 0.03095433, 0.00332366, 0.00106894])

In [146]:
Y_pred_v1=lreg_v1.predict(X_test)

In [147]:
Y_df_v1=pd.DataFrame({"Actual": Y_test, "Predicted": Y_pred_v1, "Residual": Y_test- Y_pred_v1})

In [148]:
from sklearn.metrics import mean_squared_error

In [149]:
lreg_v1.score(X_test, Y_test)

0.979948162774217

In [150]:
from sklearn.metrics import r2_score

In [151]:
r2_score(Y_df_v1.Actual, Y_df_v1.Predicted)

0.979948162774217

### K Fold Cross Validation

In [152]:
from sklearn.model_selection import cross_val_score

In [153]:
scores=cross_val_score(LinearRegression(),
                      X_train,
                      Y_train,
                      cv=5,
                      scoring='r2')

In [154]:
scores

array([0.96612485, 0.97087485, 0.96926517, 0.97593387, 0.93389054])

In [155]:
scores.std()

0.01500292431852364

In [156]:
scores.mean()

0.9632178551479843

### KNN Algorithm

In [157]:
from sklearn.neighbors import KNeighborsRegressor

In [158]:
knn_v4=KNeighborsRegressor(n_neighbors=5)

In [159]:
knn_v4.fit(X_train, Y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [160]:
knn_scores=cross_val_score(KNeighborsRegressor(n_neighbors=5),
                          X_train,
                          Y_train,
                          cv=5,
                          scoring='r2')

In [161]:
knn_scores

array([0.96657832, 0.97437228, 0.97990509, 0.97563427, 0.93836277])

In [162]:
Y_pred_v1=knn_v4.predict(X_test)

In [169]:
Y_df_v1=pd.DataFrame({"Actual": Y_test, "Predicted": Y_pred_v1, "Residual": Y_test- Y_pred_v1})

In [164]:
from sklearn.metrics import mean_squared_error

In [173]:
np.sqrt(mean_squared_error(Y_test, Y_pred_v1))

0.5622632835247197

In [166]:
from sklearn.metrics import r2_score

In [174]:
r2_score(Y_df_v1.Actual, Y_df_v1.Predicted)

0.9851234842217302

### Grid Search

In [176]:
KNeighborsRegressor?

In [195]:
params= {"n_neighbors": [4,6,8,10],
       "weights": ['uniform','distance']}

In [196]:
from sklearn.model_selection import GridSearchCV

In [197]:
knn_grid=GridSearchCV ( KNeighborsRegressor(),
                     param_grid = params,
                     cv=5,
                     scoring ='r2' )

In [198]:
knn_grid.fit(X_train, Y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                           metric='minkowski',
                                           metric_params=None, n_jobs=None,
                                           n_neighbors=5, p=2,
                                           weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid={'n_neighbors': [4, 6, 8, 10],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='r2', verbose=0)

In [202]:
knn_grid.best_params_

{'n_neighbors': 4, 'weights': 'distance'}

In [204]:
knn_grid.best_score_

0.9764274513222126

In [203]:
cv_results=knn_grid.cv_results_

In [208]:
grid_results_df=pd.DataFrame({"models": 
                           cv_results['params'],
                           "mean_score":
                           cv_results['mean_test_score'],
                           "std_score":
                           cv_results['std_test_score']})

In [210]:
grid_results_df

models  mean_score  std_score
0    {'n_neighbors': 4, 'weights': 'uniform'}    0.971463   0.012513
1   {'n_neighbors': 4, 'weights': 'distance'}    0.976427   0.012436
2    {'n_neighbors': 6, 'weights': 'uniform'}    0.963461   0.014034
3   {'n_neighbors': 6, 'weights': 'distance'}    0.971626   0.013918
4    {'n_neighbors': 8, 'weights': 'uniform'}    0.961145   0.009193
5   {'n_neighbors': 8, 'weights': 'distance'}    0.969928   0.011195
6   {'n_neighbors': 10, 'weights': 'uniform'}    0.958384   0.009253
7  {'n_neighbors': 10, 'weights': 'distance'}    0.968284   0.010682

### Deploying the model

In [212]:
from sklearn.externals import joblib

C:\Users\Meenakshi\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [213]:
joblib.dump(knn_v4,"sales.model")

['sales.model']